name: testjm
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0a08'
    - '#515560'
    - '#828886'
    - '#b1bfca'
  brandStrength: 0.09044040273874998
  lightness: 0.7307723693083972
  saturation: 0.1783299962989986
  rhythmicContrast: 0.8181155165657401
purpose: []
